<?php

namespace PaieBundle\Repository;

/**
 * Cheque_VersementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cheque_VersementRepository extends \Doctrine\ORM\EntityRepository
{
}
