<?php

namespace PaieBundle\Repository;

/**
 * Compte_HussenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compte_HussenRepository extends \Doctrine\ORM\EntityRepository
{
}
