<?php

namespace PaieBundle\Repository;

/**
 * Demande_RemboursementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_RemboursementRepository extends \Doctrine\ORM\EntityRepository
{
}
