<?php

namespace PaieBundle\Repository;

/**
 * NotificationBackendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationBackendRepository extends \Doctrine\ORM\EntityRepository
{
}
