<?php

namespace PaieBundle\Repository;

/**
 * Notification_vueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Notification_vueRepository extends \Doctrine\ORM\EntityRepository
{
}
