<?php

namespace PaieBundle\Repository;

/**
 * Numero_CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Numero_CompteRepository extends \Doctrine\ORM\EntityRepository
{
}
