<?php

namespace PaieBundle\Repository;

/**
 * RemboursementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemboursementRepository extends \Doctrine\ORM\EntityRepository
{
}
