<?php

namespace CompteAssociationBundle\Repository;

/**
 * MembreAssocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreAssocRepository extends \Doctrine\ORM\EntityRepository
{
}
