compte_association:
    resource: "@CompteAssociationBundle/Controller/"
    type:     annotation
    prefix:   /

compte_groupe:
    resource: "@CompteGroupeBundle/Resources/config/routing.yml"
    prefix:   /

demande_qh:
    resource: "@DemandeQhBundle/Resources/config/routing.yml"
    prefix:   /demande-QH

back_office:
  resource: "@BackBundle/Resources/config/routing.yml"
  prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

paie:
    resource: "@PaieBundle/Resources/config/routing.yml"
    prefix:   /Hussen-Scheme

personne:
    resource: "@PersonneBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user-admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"