<?php

namespace BackBundle\Repository;

/**
 * Compte_CaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compte_CaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
