<?php

namespace BackBundle\Repository;

/**
 * Historique_CaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_CaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
