<?php

namespace BackBundle\Repository;

/**
 * notifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notifRepository extends \Doctrine\ORM\EntityRepository
{
}
