<?php

namespace DemandeQhBundle\Repository;

/**
 * ConfirmationDemandeQhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmationDemandeQhRepository extends \Doctrine\ORM\EntityRepository
{
}
