<?php

namespace DemandeQhBundle\Repository;

/**
 * ConirmationQHRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConirmationQHRepository extends \Doctrine\ORM\EntityRepository
{
}
