<?php

namespace DemandeQhBundle\Repository;

/**
 * DemandeQhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeQhRepository extends \Doctrine\ORM\EntityRepository
{
}
