<?php

namespace DemandeQhBundle\Repository;

/**
 * DemandeQhsocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeQhsocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
