<?php

namespace DemandeQhBundle\Repository;

/**
 * DemandeQh_societeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeQh_societeRepository extends \Doctrine\ORM\EntityRepository
{
}
