<?php

namespace DemandeQhBundle\Repository;

/**
 * EtatSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
