<?php

namespace DemandeQhBundle\Repository;

/**
 * EtatDemandeQhSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatDemandeQhSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
