<?php

namespace DemandeQhBundle\Repository;

/**
 * GarantieOrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarantieOrRepository extends \Doctrine\ORM\EntityRepository
{
}
