<?php

namespace DemandeQhBundle\Repository;

/**
 * GarantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarantRepository extends \Doctrine\ORM\EntityRepository
{
}
