<?php

namespace DemandeQhBundle\Repository;

/**
 * Mambres_societeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mambres_societeRepository extends \Doctrine\ORM\EntityRepository
{
}
