<?php

namespace DemandeQhBundle\Repository;

/**
 * Membres_societeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Membres_societeRepository extends \Doctrine\ORM\EntityRepository
{
}
