<?php

namespace DemandeQhBundle\Repository;

/**
 * ModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificationRepository extends \Doctrine\ORM\EntityRepository
{
}
