<?php

namespace DemandeQhBundle\Repository;

/**
 * MozeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MozeRepository extends \Doctrine\ORM\EntityRepository
{
}
