<?php

namespace DemandeQhBundle\Repository;

/**
 * NumeroQH_demandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroQH_demandeRepository extends \Doctrine\ORM\EntityRepository
{
}
