<?php

namespace DemandeQhBundle\Repository;

/**
 * PhotoOrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoOrRepository extends \Doctrine\ORM\EntityRepository
{
}
