<?php

namespace DemandeQhBundle\Repository;

/**
 * SocieteDemandeQHRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocieteDemandeQHRepository extends \Doctrine\ORM\EntityRepository
{
}
